"user client"
import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "@/context/authProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`antialiased`}
        >
          {children}

        </body>
      </AuthProvider>
    </html>
  );
}
